apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: todo-react
  title: To-do in React
  description: A web-based To-do application, written in React. For demonstration purposes only!
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - react
    - website
spec:
  type: service
  lifecycle: experimental
  owner: dev-support
